apiVersion: apps/v1
kind: Deployment
metadata:
  name: balancereader
  namespace: balancereader
spec:
  selector:
    matchLabels:
      app: balancereader
  template: 
    spec: 
      containers:
      - name: balancereader
        env:
        - name: ENABLE_TRACING
          value: "false"
        - name: ENABLE_METRICS
          value: "false"
        - name: LOG_LEVEL
          value: "debug"