apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerwriter
  namespace: ledgerwriter
spec:
  selector:
    matchLabels:
      app: ledgerwriter
  template: 
    spec: 
      containers:
      - name: ledgerwriter
        env:
        - name: ENABLE_TRACING
          value: "false"
        - name: ENABLE_METRICS
          value: "false"
        - name: LOG_LEVEL
          value: "debug"