apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionhistory
  namespace: transactionhistory
spec:
  selector:
    matchLabels:
      app: transactionhistory
  template: 
    spec: 
      containers:
      - name: transactionhistory
        env:
        - name: ENABLE_TRACING
          value: "false"
        - name: ENABLE_METRICS
          value: "false"
        - name: LOG_LEVEL
          value: "debug"