apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: userservice
spec:
  selector:
    matchLabels:
      app: userservice
  template: 
    spec: 
      containers:
      - name: userservice
        env:
        - name: ENABLE_TRACING
          value: "false"
        - name: ENABLE_METRICS
          value: "false"
        - name: LOG_LEVEL
          value: "debug"