apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  template: 
    spec: 
      containers:
      - name: loadgenerator
        image: gcr.io/bank-of-anthos/loadgenerator:v0.4.3
        env:
        - name: LOG_LEVEL
          value: "info"