apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: userservice
spec:
  selector:
    matchLabels:
      app: userservice
  template: 
    spec: 
      containers:
      - name: userservice
        image: gcr.io/bank-of-anthos/userservice:v0.4.3
        env:
        - name: ENABLE_TRACING
          value: "true"
        - name: ENABLE_METRICS
          value: "true"
        - name: LOG_LEVEL
          value: "info"