# apiVersion: v1
# kind: Namespace
# metadata:
#   name: loadgenerator
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
        org: cymbal-bank
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: cymbal-ksa
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
      - name: loadgenerator
        image: gcr.io/krm-test-3/cymbal-bank/release/loadgenerator:61b0f15
        env:
        - name: FRONTEND_ADDR
          value: "frontend:80"
        - name: USERS
          value: "5"
        - name: LOG_LEVEL
          value: "error"
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
